### ISSUE TITLE
krun autofill broken

### ISSUE THREAD

**Issue by pdaian** [kframework/kweb#23]
When using the K tool on KWeb, clicking a kompiled definition followed by a program neither autofills the krun box nor adds the appropriate ("-d") arguments to kompile.

Steps to reproduce:
- Chrome + Linux
- http://www.kframework.org/index.php/Lesson_1,_LAMBDA:_Syntax_Modules_and_Basic_K_Commands
- Click expand
- Click lambda.k
- Click any program under tests
- KRun box not autofilled

**Comment by kheradmand** [comment]
fixed :+1:
